@startuml
title Contact information lookup sequence diagram

participant "External system" as ext  #99FF99

ext -> api : POST to send email with lookup: /v2/notifications/lookup/email
activate api
note right of ext
  ""{""
  ""  templated_id: abcd""
  ""  participant_id: 1234""
  ""}""
end note

database database
api -> database: persist notification with blank email, Participant ID, and status "REQUIRES_LOOKUP"

queue queue
api -> queue: enqueue **lookup_email** task

api -> ext: Partial response
note right of ext
  ""{""
  ""  id: xyz""
  ""}""
end note
deactivate api

...

celery -> queue: dequeue **lookup_email** task
activate celery

celery -> database: get notification

database -> celery: notification, with Participant ID

box External services #f3f3f3

participant "VA Profile" as vaprofile

participant "Master Person Index" as mpi

celery -> vaprofile: get Vet360ID for this Participant ID

vaprofile -> mpi: get Vet360ID for this Participant ID

mpi -> vaprofile: Vet360ID

vaprofile -> celery: Vet360ID

celery -> vaprofile: get contact info for this Vet360ID

vaprofile -> celery: contact info
end box

celery -> database: update notification to persist email address
celery -> database: update notification status to indicate readiness

celery -> queue: enqueue **deliver_email** task
deactivate celery

...

celery -> queue: dequeue **deliver_email** task
activate celery

celery -> celery
rnote right: Send email
@enduml