@startuml

[*] --> created

created -right-> sending: Pinpoint accepts

created -down-> failure: Pinpoint rejects

sending -down-> sent: record_status: SUCCESSFUL

sent -right-> delivered:  record_status: DELIVERED

sending --> failure: record_status: INVALID
sending -right-> sending: record_status in [UNREACHABLE, UNKNOWN, CARRIER_UNREACHABLE, TTL_EXPIRED]

sent --> failure: record_status in [BLOCKED, SPAM, CARRIER_BLOCKED, MAX_PRICE_EXCEEDED]

@enduml