changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: Major Changes
      labels:
        - major
    - title: Other Changes
      labels:
        - "*"
