repos:
    - repo: https://github.com/thoughtworks/talisman
      rev: 'v1.27.0'
      hooks:
          - id: talisman-commit
    - repo: https://github.com/PyCQA/bandit
      rev: '1.7.4'
      hooks:
          - id: bandit
            args: [-c, .bandit.yml, -r, -l]
    - repo: https://gitlab.com/pycqa/flake8
      rev: '3.7.9'
      hooks:
          - id: flake8
            args: [--config, .flake8]
            exclude: |
              (?x)(
                ^venv*|
                ^__pycache__|
                ^node_modules|
                ^cache|
                ^migrations|
                ^build|
                ^lambda_functions
              )
            
