repos:
  - repo: https://github.com/thoughtworks/talisman
    rev: "v1.32.0"
    hooks:
      - id: talisman-commit
        entry: cmd --githook pre-commit
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.9"
    hooks:
      - id: bandit
        args: [-c, pyproject.toml, -r, -l]
        additional_dependencies: ["bandit[toml]"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: "v0.5.5"
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
