repos:
    - repo: https://github.com/thoughtworks/talisman
      rev: 'v1.27.0'
      hooks:
          - id: talisman-commit
    - repo: https://github.com/PyCQA/bandit
      rev: '1.7.4'
      hooks:
          - id: bandit
            args: [-c, .bandit.yml, -r, -l]
    - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      rev: v0.1.9
      hooks:
        # Run the linter.
        - id: ruff
          args: [ --fix ]
        # Run the formatter.
        - id: ruff-format
