apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: notification-api
  description: GC Notify API | GC Notification API
  labels:
    license: MIT
spec:
  type: website
  lifecycle: experimental
  owner: cds-snc
