steps:
- name: "gcr.io/cloud-builders/gcloud"
  args:
    - kms
    - decrypt
    - --ciphertext-file=.env.enc
    - --plaintext-file=.env
    - --location=global
    - --project=$PROJECT_ID
    - --keyring=deploy
    - --key=env
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'build',
      '-t',
      'local_test',
      '.',
    ]
- name: "local_test"
  args: ["make test"]
