FROM python:3.6-slim-stretch

ENV DEBIAN_FRONTEND noninteractive
ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8
# Python, don't write bytecode!
ENV PYTHONDONTWRITEBYTECODE 1

RUN apt-get update
RUN apt-get install -y build-essential software-properties-common git

# update pip
RUN python -m pip install pip --upgrade
RUN python -m pip install wheel

CMD ["/bin/bash"]