[tool.ruff]
target-version = "py310"
exclude = ["venv*", "__pycache__", "node_modules", "cache", "migrations", "build"]
extend-include = ['(app|migrations|tests)/.*\.pyi?$']
src = ["app", "migrations", "tests"]
# Ruff formatter will wrap lines at a length of 130 characters.
line-length = 130
indent-width = 4

[tool.ruff.lint]
select = [
    # PyFlakes
    "F",
    # Pycodestyle
    "E",
    "W",
    # isort
    "I001",
    "I002"
]
ignore = ["E203", "E501", "E402"]

# Provide line length leeway for docstrings
[tool.ruff.lint.pycodestyle]
max-doc-length = 170
# Enforce doc string format? (google, numpy or pep257)
# convention = "google"

[tool.ruff.format]
# Match black formatting
# Double quotes for strings.
quote-style = "double"
# Indent with spaces, rather than tabs.
indent-style = "space"
# Respect magic trailing commas.
skip-magic-trailing-comma = false
# Automatically detect the appropriate line ending.
line-ending = "auto"

[tool.poetry]
name = "notification-api"
version = "0.1.0"
description = "Public-facing REST API for Notification built on the GOV.UK Notify platform."
authors = ["Canadian Digital Service"]
license = "MIT license"
readme = "README.md"
packages = []

[tool.poetry.scripts]
notify-api = ""

[build-system]
requires = ["poetry>=1.3.2"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = "~3.10.9"
apig-wsgi = "2.18.0"
aws-embedded-metrics = "1.0.8"
# PaaS
awscli-cwlogs = "1.4.6"
boto = "2.49.0"
cachelib = "0.10.2"
celery = {extras = ["sqs"], version = "5.3.6"}

# Pinned dependencies
certifi = "^2023.7.22" # pinned for security reasons: https://github.com/cds-snc/notification-api/security/dependabot/119
cffi = "1.15.1"
click-datetime = "0.2"
cryptography = "^41.0.2" # pinned for security reasons: https://github.com/cds-snc/notification-api/security/dependabot/118
docopt = "0.6.2"
environs = "9.5.0" # pyup: <9.3.3 # marshmallow v3 throws errors"
fido2 = "0.9.3"
#git+https://github.com/mitsuhiko/flask-sqlalchemy.git@500e732dd1b975a56ab06a46bd1a20a21e682262#egg=Flask-SQLAlchemy==2.3.2.dev20190108
Flask = "2.3.3"
Flask-Bcrypt = "1.0.1"
flask-marshmallow = "0.14.0"
Flask-Migrate = "2.7.0"
Flask-SQLAlchemy = { git = "https://github.com/pallets-eco/flask-sqlalchemy.git", rev = "500e732dd1b975a56ab06a46bd1a20a21e682262"}
gevent = "23.9.1"
greenlet = "2.0.2"
gunicorn = "20.1.0"
idna = "2.10" # pinned to align with test moto dependency requirements (for <=2.9)
iso8601 = "2.0.0"
# REVIEW: v2 is using sha512 instead of sha1 by default (in v1)
itsdangerous = "2.1.2"
jsonschema = "3.2.0"
MarkupSafe = "2.1.4"
marshmallow = "3.20.2"
marshmallow-sqlalchemy = "0.29.0"
more-itertools = "8.14.0"
nanoid = "2.0.0"
newrelic = "6.10.0.165"
notifications-python-client = "6.4.1"
notifications-utils = { git = "https://github.com/cds-snc/notifier-utils.git", rev = "2da74685e0ffb220f0403e1f2584e783be99bbad" }
psycopg2-binary = "2.9.9"
pwnedpasswords = "2.0.0"
PyJWT = "2.8.0"
python-dotenv = "1.0.1"
python-magic = "0.4.27"
pytz = "2021.3"
PyYAML = "6.0.1"
simple-salesforce = "^1.12.3"
SQLAlchemy = "1.4.51"
tldextract = "3.4.4"
# rsa = "4.9  # awscli 1.22.38 depends on rsa<4.8
typing-extensions = "4.7.1"
unidecode = "1.3.8"
# Putting upgrade on hold due to new version introducing breaking changes
Werkzeug = "2.3.7"


[tool.poetry.group.test.dependencies]
coveralls = "3.3.1"
freezegun = "1.2.2"
idna = "2.10"
# used for creating manifest file locally
jinja2-cli = { extras = ["yaml"], version = "0.8.2" }
locust = "2.16.1"
moto = "4.1.11"
mypy = "1.5"
networkx = "2.8.8" # not directly required, pinned by Snyk to avoid a vulnerability
pytest = "7.4.4"
pytest-cov = "3.0.0"
pytest-env = "0.8.2"
pytest-mock = "3.11.1"
pytest-mock-resources = { extras = ["redis"], version = "2.9.2" }
pytest-xdist = "2.5.0"
requests-mock = "1.11.0"
rfc3987 = "1.3.8"
ruff = "^0.2.1"
sqlalchemy-stubs = "0.4"
sqlalchemy2-stubs = "0.0.2a38"
# optional requirements for jsonschema
strict-rfc3339 = "0.7"
types-boto = "2.49.18.9"
types-mock = "4.0.15.2"
types-python-dateutil = "2.8.19.20240106"
types-pytz = "2022.7.1.2"
types-redis = "4.6.0.20240106"
types-requests = "2.31.0.20240106"
