openapi: 3.0.3
info:
  title: Notifications API
  description: API for sending SMS and email notifications
  version: 2.0.0

paths:
  /v2/notifications/sms:
    post:
      summary: Send a text message
      description: |
        Send a text message to a recipient phone number using a template.
        
        The template can include placeholders which are populated using the personalisation parameter.
      operationId: sendSmsNotification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostSmsRequest'
      responses:
        '201':
          description: SMS notification sent successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostSmsResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden - not authorized to use the API key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: Rate limit exceeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - apiKey: []
  
  /v2/notifications/email:
    post:
      summary: Send an email notification
      description: |
        Send an email notification to a recipient email address using a template.
        
        The template can include placeholders which are populated using the personalisation parameter.        
      operationId: sendEmailNotification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostEmailRequest'
      responses:
        '201':
          description: Email notification sent successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostEmailResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden - not authorized to use the API key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: Rate limit exceeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - apiKey: []
  

  
  /v2/notifications/bulk:
    post:
      summary: Send a batch of notifications
      description: |
        Send notifications in bulk, up to 50,000 recipients at a time, for a single template. 
        
        You can schedule to send notifications up to 4 days in advance.
      operationId: sendBulkNotifications
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostBulkRequest'
      responses:
        '201':
          description: Bulk job created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostBulkResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden - not authorized to use the API key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: Rate limit exceeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - apiKey: []

components:
  schemas:
    UUID:
      type: string
      format: uuid
      pattern: "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
      example: "123e4567-e89b-12d3-a456-426614174000"
    
    PostSmsRequest:
      type: object
      required:
        - template_id
        - phone_number
      properties:
        template_id:
          $ref: '#/components/schemas/UUID'
          description: The ID of text message template you want to send.
        phone_number:
          type: string
          description: The phone number to send the SMS to
          example: "+19021234567"
        personalisation:
          type: object
          description: Use if a template has placeholder fields for personalised information such as name or reference number
          additionalProperties: true
          example:
            first_name: "Amala"
            appointment_date: "2023-01-01"
        reference:
          type: string
          description: An identifier you can create if necessary. This reference identifies a single notification or a batch of notifications.
          example: "STRING"
        sms_sender_id:
          $ref: '#/components/schemas/UUID'
          description: A unique identifier of the sender of the text message notification
      
    PostEmailRequest:
      type: object
      required:
        - template_id
        - email_address
      properties:
        template_id:
          $ref: '#/components/schemas/UUID'
          description: The ID of the email template you want to send.
        email_address:
          type: string
          format: email
          description: The email address of the recipient
          example: "sender@something.com"
        personalisation:
          type: object
          description: Use if a template has placeholder fields for personalised information such as name or reference number
          example:
            first_name: "Amala"
            application_date: "2023-01-01"
        reference:
          type: string
          description: An identifier you can create if necessary. This reference identifies a single notification or a batch of notifications. It must not contain any personal information such as name or postal address.
          example: "STRING"
        email_reply_to_id:
          $ref: '#/components/schemas/UUID'
          description: The ID of an email address specified by you to receive replies from your users.
    

    
    PostBulkRequest:
      type: object
      required:
        - template_id
        - name
      properties:
        template_id:
          $ref: '#/components/schemas/UUID'
        name:
          type: string
          description: The name of your bulk sending job. Used to identify this bulk of notifications later on.
          example: "January Appointment Reminders"
        reference:
          type: string
          description: A reference for this batch
          example: "batch-reference-123"
        csv:
          type: string
          format: binary
          description: If you prefer to pass the content of CSV files instead of rows in the rows argument, you can do so. Pass the full content of your CSV file in a key named csv. Do not include the rows argument.
          example: "email address,name\nalice@example.com,Alice"
        rows:
          type: array
          description: An array of arrays. The first line is the header and should include at least email address if you're sending an email template or phone number if you're sending a text message template. The other column headers should match the placeholder fields (personalised variables) of your template. The following lines should be your recipients' details and should match the order of column headers. You can have between 1 and 50,000 recipients.
          items:
            type: array
            items:
              type: string
          example:
            - ["email address", "name"]
            - ["alice@example.com", "Alice"]
            - ["bob@example.com", "Bob"]
        scheduled_for:
          type: string
          format: date-time
          description: If you want to send notifications in the future, you can specify a datetime up to 4 days in the future, in ISO 8601 format, UTC time.
          example: "2023-01-01T12:00:00"
          nullable: true
        reply_to_id:
          $ref: '#/components/schemas/UUID'
          description: The ID of the reply-to address or phone number to use
          nullable: true
    
    PostSmsResponse:
      type: object
      required:
        - id
        - content
        - uri
        - template
      properties:
        id:
          $ref: '#/components/schemas/UUID'
        reference:
          type: string
          nullable: true
        content:
          type: object
          properties:
            body:
              type: string
              description: The SMS message body
            from_number:
              type: string
              description: The phone number the SMS was sent from
        uri:
          type: string
          format: uri
        template:
          type: object
          properties:
            id:
              $ref: '#/components/schemas/UUID'
            version:
              type: integer
            uri:
              type: string
              format: uri
    
    PostEmailResponse:
      type: object
      required:
        - id
        - content
        - uri
        - template
      properties:
        id:
          $ref: '#/components/schemas/UUID'
        reference:
          type: string
          nullable: true
        content:
          type: object
          properties:
            body:
              type: string
              description: The email body
            subject:
              type: string
              description: The email subject
            from_email:
              type: string
              format: email
              description: The email address the email was sent from
        uri:
          type: string
          format: uri
        template:
          type: object
          properties:
            id:
              $ref: '#/components/schemas/UUID'
            version:
              type: integer
            uri:
              type: string
              format: uri
    

    
    ErrorResponse:
      type: object
      properties:
        status_code:
          type: integer
          description: HTTP status code
        errors:
          type: array
          items:
            type: object
            properties:
              error:
                type: string
                description: Error message
              message:
                type: string
                description: Detailed error message
    
    PostBulkResponse:
      type: object
      properties:
        data:
          type: object
          required:
            - id
            - template
            - job_status
          properties:
            id:
              $ref: '#/components/schemas/UUID'
              description: The ID of the bulk notification job
            original_file_name:
              type: string
              description: The name of the original CSV file if one was provided
            notification_count:
              type: integer
              description: The number of notifications in the bulk job
            template:
              $ref: '#/components/schemas/UUID'
              description: The ID of the template used for this notification job
            job_status:
              type: string
              enum: ['pending', 'scheduled']
              description: The status of the bulk notification job
            scheduled_for:
              type: string
              format: date-time
              nullable: true
              description: When the job is scheduled to be processed, null if immediate

  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: Authorization
      description: API Key with format 'Bearer {api_key}'
