from enum import Enum
import os


class FeatureFlag(Enum):
    CHECK_TEMPLATE_NAME_EXISTS_ENABLED = 'CHECK_TEMPLATE_NAME_EXISTS_ENABLED'
    EMAIL_DELIVERY_STATUS_OVERHAUL = 'EMAIL_DELIVERY_STATUS_OVERHAUL'
    PINPOINT_SMS_VOICE_V2 = 'PINPOINT_SMS_VOICE_V2'
    PLATFORM_STATS_ENABLED = 'PLATFORM_STATS_ENABLED'
    PII_ENABLED = 'PII_ENABLED'
    SERVICE_EMAIL_FALLBACK_ENABLED = 'SERVICE_EMAIL_FALLBACK_ENABLED'
    STORE_TEMPLATE_CONTENT = 'STORE_TEMPLATE_CONTENT'
    V3_ENABLED = 'V3_ENABLED'
    VA_PROFILE_SMS_STATUS_ENABLED = 'VA_PROFILE_SMS_STATUS_ENABLED'


def is_feature_enabled(feature_flag):
    return isinstance(feature_flag, FeatureFlag) and os.getenv(feature_flag.value, 'False') == 'True'
