from enum import Enum
import os


PROVIDER_FEATURE_FLAGS = {
    'govdelivery': 'GOVDELIVERY_EMAIL_CLIENT_ENABLED'
}


class FeatureFlag(Enum):
    ACCEPT_RECIPIENT_IDENTIFIERS_ENABLED = 'ACCEPT_RECIPIENT_IDENTIFIERS_ENABLED'
    TEMPLATE_SERVICE_PROVIDERS_ENABLED = 'TEMPLATE_SERVICE_PROVIDERS_ENABLED'
    PROVIDER_STRATEGIES_ENABLED = 'PROVIDER_STRATEGIES_ENABLED'
    PINPOINT_RECEIPTS_ENABLED = 'PINPOINT_RECEIPTS_ENABLED'
    PINPOINT_INBOUND_SMS_ENABLED = 'PINPOINT_INBOUND_SMS_ENABLED'
    NOTIFICATION_FAILURE_REASON_ENABLED = 'NOTIFICATION_FAILURE_REASON_ENABLED'
    GITHUB_LOGIN_ENABLED = 'GITHUB_LOGIN_ENABLED'
    EMAIL_PASSWORD_LOGIN_ENABLED = 'EMAIL_PASSWORD_LOGIN_ENABLED'  # nosec
    CHECK_GITHUB_SCOPE_ENABLED = 'CHECK_GITHUB_SCOPE_ENABLED'
    CHECK_RECIPIENT_COMMUNICATION_PERMISSIONS_ENABLED = 'CHECK_RECIPIENT_COMMUNICATION_PERMISSIONS_ENABLED'
    SMS_SENDER_RATE_LIMIT_ENABLED = 'SMS_SENDER_RATE_LIMIT_ENABLED'
    CHECK_TEMPLATE_NAME_EXISTS_ENABLED = 'CHECK_TEMPLATE_NAME_EXISTS_ENABLED'
    EMAIL_ATTACHMENTS_ENABLED = 'EMAIL_ATTACHMENTS_ENABLED'
    NIGHTLY_NOTIF_CSV_ENABLED = 'NIGHTLY_NOTIF_CSV_ENABLED'
    PUSH_NOTIFICATIONS_ENABLED = 'PUSH_NOTIFICATIONS_ENABLED'
    PLATFORM_STATS_ENABLED = 'PLATFORM_STATS_ENABLED'
    VA_SSO_ENABLED = 'VA_SSO_ENABLED'
    V3_ENABLED = 'V3_ENABLED'
    COMP_AND_PEN_MESSAGES_ENABLED = 'COMP_AND_PEN_MESSAGES_ENABLED'


def is_provider_enabled(current_app, provider_identifier):
    if provider_identifier in PROVIDER_FEATURE_FLAGS:
        return current_app.config.get(PROVIDER_FEATURE_FLAGS[provider_identifier])
    else:
        return True


def accept_recipient_identifiers_enabled():
    return is_feature_enabled(FeatureFlag.ACCEPT_RECIPIENT_IDENTIFIERS_ENABLED)


def is_gapixel_enabled(current_app):
    return current_app.config.get('GOOGLE_ANALYTICS_ENABLED')


def is_feature_enabled(feature_flag):
    return isinstance(feature_flag, FeatureFlag) and os.getenv(feature_flag.value, 'False') == 'True'
