"""

Revision ID: 0297a_add_sns_provider
Revises: 0297_template_redacted_fix
Create Date: 2019-07-09 08:49:20.630174

"""
from alembic import op
import sqlalchemy as sa


revision = '0297a_add_sns_provider'
down_revision = '0297_template_redacted_fix'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'complaints', 'notification_history', ['notification_id'], ['id'])
    op.alter_column('notification_history', 'international',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('notifications', 'international',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index('ix_notifications_service_created_at', table_name='notifications')
    op.alter_column('services_history', 'prefix_sms',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###

    op.execute("""
        INSERT INTO provider_details (display_name, identifier, priority, notification_type, active, version) 
        VALUES ('AWS SNS', 'sns', 0, 'sms', true, 1)
    """)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('services_history', 'prefix_sms',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_index('ix_notifications_service_created_at', 'notifications', ['service_id', 'created_at'], unique=False)
    op.alter_column('notifications', 'international',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('notification_history', 'international',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    # ### end Alembic commands ###

    op.execute("DELETE FROM provider_details WHERE name = 'sns'")
