"""

Revision ID: 0342_add_reply_to_field
Revises: 0341_drop_ck_on_idp_user_id
Create Date: 2022-03-24 15:48:44.002785

"""
from alembic import op
import sqlalchemy as sa

revision = '0342_add_reply_to_field'
down_revision = '0341_drop_ck_on_idp_user_id'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('reply_to_email', sa.String(length=254), nullable=True))
    op.add_column('templates_history', sa.Column('reply_to_email', sa.String(length=254), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates_history', 'reply_to_email')
    op.drop_column('templates', 'reply_to_email')
    # ### end Alembic commands ###
