"""

Revision ID: 0348_updated_stored_function.py
Revises: 0347_modify_table_and_function
Create Date: 2022-06-01 17:44:13.237873

"""
from alembic import op
from alembic_utils.pg_function import PGFunction

revision = '0348_updated_stored_function'
down_revision = '0347_modify_table_and_function'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    public_va_profile_opt_in_out = PGFunction(
        schema="public",
        signature="va_profile_opt_in_out(_va_profile_id integer, _communication_item_id integer, _communication_channel_id integer, _allowed Boolean, _source_datetime timestamp)",
        definition='RETURNS boolean AS\n$$\nDECLARE number_of_changed_records Int;\nBEGIN\nINSERT INTO va_profile_local_cache(va_profile_id, communication_item_id, communication_channel_id, source_datetime, allowed)\n    VALUES(_va_profile_id, _communication_item_id, _communication_channel_id, _source_datetime, _allowed)\n\tON CONFLICT ON CONSTRAINT uix_veteran_id DO UPDATE\n    SET allowed = _allowed, source_datetime = _source_datetime\n    WHERE _source_datetime > va_profile_local_cache.source_datetime\n        AND va_profile_local_cache.va_profile_id = _va_profile_id\n        AND va_profile_local_cache.communication_item_id = _communication_item_id\n        AND va_profile_local_cache.communication_channel_id = _communication_channel_id;\nGET DIAGNOSTICS number_of_changed_records = ROW_COUNT; \nRETURN number_of_changed_records > 0; \nEND\n$$\nLANGUAGE plpgsql'
    )
    op.replace_entity(public_va_profile_opt_in_out)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    public_va_profile_opt_in_out = PGFunction(
        schema="public",
        signature="va_profile_opt_in_out(_va_profile_id integer, _communication_item_id integer, _communication_channel_id integer, _allowed boolean, _source_datetime timestamp without time zone)",
        definition='returns boolean\n LANGUAGE sql\nAS $function$\nINSERT INTO va_profile_local_cache(va_profile_id, communication_item_id, communication_channel_id, source_datetime, allowed)\n    VALUES(_va_profile_id, _communication_item_id, _communication_channel_id, _source_datetime, _allowed)\n\tON CONFLICT ON CONSTRAINT uix_veteran_id DO UPDATE\n    SET allowed = _allowed, source_datetime = _source_datetime\n    WHERE _source_datetime > va_profile_local_cache.source_datetime\n        AND va_profile_local_cache.va_profile_id = _va_profile_id\n        AND va_profile_local_cache.communication_item_id = _communication_item_id\n        AND va_profile_local_cache.communication_channel_id = _communication_channel_id\n    RETURNING true\n$function$'
    )
    op.replace_entity(public_va_profile_opt_in_out)
    # ### end Alembic commands ###
