"""

Revision ID: 0349_delete_old_opt_out_function
Revises: 0348_updated_stored_function
Create Date: 2022-06-24 20:17:44.141953

"""
from alembic import op
from alembic_utils.pg_function import PGFunction

revision = '0349_delete_old_opt_out_function'
down_revision = '0348_updated_stored_function'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    public_va_profile_remove_old_opt_outs = PGFunction(
        schema="public",
        signature="va_profile_remove_old_opt_outs()",
        definition="RETURNS void AS\n  $$\nDELETE\nFROM va_profile_local_cache\nWHERE allowed = False \nAND age(NOW(), source_datetime) > INTERVAL '24 hours';\n$$\nLANGUAGE sql"
    )
    op.create_entity(public_va_profile_remove_old_opt_outs)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    public_va_profile_remove_old_opt_outs = PGFunction(
        schema="public",
        signature="va_profile_remove_old_opt_outs()",
        definition="RETURNS void AS\n  $$\nDELETE\nFROM va_profile_local_cache\nWHERE allowed = False \nAND age(NOW(), source_datetime) > INTERVAL '24 hours';\n$$\nLANGUAGE sql"
    )
    op.drop_entity(public_va_profile_remove_old_opt_outs)

    
    # ### end Alembic commands ###
