"""

Revision ID:0369a_va_profile_cache_fields
Revises: 0369_va_profile_cache_fields
Create Date: 2024-08-05 15:10:01

"""
from alembic import op
import sqlalchemy as sa

revision = '0369a_va_profile_cache_fields'
down_revision = '0369_va_profile_cache_fields'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('va_profile_local_cache', 'va_profile_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('va_profile_local_cache', 'participant_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():

    # Update participant_id to -1 where it cannot be converted back to INTEGER
    op.execute("""
        UPDATE va_profile_local_cache
        SET participant_id = -1
        WHERE participant_id > 2147483647
    """)
    
    # Delete rows where va_profile_id cannot be converted back to INTEGER
    op.execute("""
        DELETE FROM va_profile_local_cache
        WHERE va_profile_id > 2147483647
    """)


    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('va_profile_local_cache', 'participant_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('va_profile_local_cache', 'va_profile_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
