"""

Revision ID: 0498_add_table_metadata
Revises: 0497_newsletter_service
Create Date: 2025-12-02 00:00:00.000000

"""
from alembic import op

revision = '0498_add_table_metadata'
down_revision = '0497_newsletter_service'

COMMENTS = {
    "jobs": {
        "id": "Unique identifier for each job. Primary key for the table.",
        "original_file_name": "Name of the file that was uploaded to create this job.",
        "service_id": "Foreign key linking to the service running the job.",
        "template_id": "Foreign key referencing the template used for notifications in this job.",
        "created_at": "Date and time when the job was created.",
        "updated_at": "Date and time when the job was last updated.",
        "notification_count": "Total number of notifications to be sent in this job.",
        "notifications_sent": "Number of notifications that have been sent.",
        "processing_started": "Date and time when the job started being processed.",
        "processing_finished": "Date and time when the job finished processing.",
        "created_by_id": "Foreign key referencing the user who created this job.",
        "template_version": "Version number of the template used for this job.",
        "notifications_delivered": "Number of notifications successfully delivered to recipients.",
        "notifications_failed": "Number of notifications that failed to deliver.",
        "job_status": "Status of the job.",
        "scheduled_for": "Date and time when the job is scheduled to run, for delayed notifications.",
        "archived": "Flag indicating whether the job has been archived.",
        "api_key_id": "Foreign key referencing the API key used to create this job.",
        "sender_id": "Sender identity used for this job.",
    },
    "login_events": {
        "id": "Unique identifier for each login event",
        "user_id": "Foreign key referencing the user that logged in..",
        "created_at": "Date and time when the login event was created.",
        "updated_at": "Date and time when the login event was updated.",
    },
    "notification_history": {
        "id": "Unique identifier for each notification record.",
        "job_id": "Foreign key reference to the batch job that generated this notification.",
        "job_row_number": "Sequential number indicating the position of this notification within its parent job.",
        "service_id": "Foreign key reference to the service that sent the notification.",
        "template_id": "Foreign key reference to the message template used for this notification.",
        "template_version": "Version number of the template used.",
        "api_key_id": "Foreign key reference to the API key used to authenticate the notification request.",
        "key_type": "Type of API key used.",
        "notification_type": "Categorization of notification (email or sms).",
        "created_at": "Date and time when the notification record was created.",
        "sent_at": "Date and time when the notification was sent.",
        "updated_at": "Date and time when the notification record was updated.",
        "reference": "AWS provided message ID of the notification.",
        "billable_units": "Number of billing units consumed by this notification. For SMS this is the number of message fragments.",
        "client_reference": "Customer-provided reference for their own tracking purposes.",
        "international": "Flag indicating whether the notification was sent internationally.",
        "phone_prefix": "Country code prefix for phone numbers in SMS notifications.",
        "rate_multiplier": "Pricing multiplier applied to SMS notifications based on the billable_units.",
        "notification_status": "Status of the notification.",
        "created_by_id": "Identifier for the user that initiated the notification.",
        "queue_name": "Name of the processing queue this notification was handled by.",
        "feedback_type": "Category of delivery feedback received.",
        "feedback_subtype": "More specific feedback classification.",
        "ses_feedback_id": "Amazon SES specific feedback identifier for email notifications.",
        "ses_feedback_date": "Date and time when feedback was received from Amazon SES.",
        "sms_total_message_price": "Total cost charged for the SMS message.",
        "sms_total_carrier_fee": "Portion of the total cost that goes to the carrier.",
        "sms_iso_country_code": "ISO country code for the destination of the SMS.",
        "sms_carrier_name": "Name of the carrier that delivered the SMS message.",
        "sms_message_encoding": "Character encoding used for the SMS message.",
        "sms_origination_phone_number": "Phone number that sent the SMS message.",
        "feedback_reason": "Pinpoint failure reason when an SMS message cannot be delivered.",
    },
    "notifications": {
        "id": "Unique identifier for each notification record.",
        "job_id": "Foreign key reference to the batch job that generated this notification.",
        "job_row_number": "Sequential number indicating the position of this notification within its parent job.",
        "service_id": "Foreign key reference to the service that sent the notification.",
        "template_id": "Foreign key reference to the message template used for this notification.",
        "template_version": "Version number of the template used.",
        "api_key_id": "Foreign key reference to the API key used to authenticate the notification request.",
        "key_type": "Type of API key used.",
        "notification_type": "Categorization of notification (email or sms).",
        "created_at": "Date and time when the notification record was created.",
        "sent_at": "Date and time when the notification was sent.",
        "updated_at": "Date and time when the notification record was updated.",
        "reference": "AWS provided message ID of the notification.",
        "billable_units": "Number of billing units consumed by this notification. For SMS this is the number of message fragments.",
        "client_reference": "Customer-provided reference for their own tracking purposes.",
        "international": "Flag indicating whether the notification was sent internationally.",
        "phone_prefix": "Country code prefix for phone numbers in SMS notifications.",
        "rate_multiplier": "Pricing multiplier applied to SMS notifications based on the billable_units.",
        "notification_status": "Status of the notification.",
        "created_by_id": "Identifier for the user that initiated the notification.",
        "queue_name": "Name of the processing queue this notification was handled by.",
        "feedback_type": "Category of delivery feedback received.",
        "feedback_subtype": "More specific feedback classification.",
        "ses_feedback_id": "Amazon SES specific feedback identifier for email notifications.",
        "ses_feedback_date": "Date and time when feedback was received from Amazon SES.",
        "sms_total_message_price": "Total cost charged for the SMS message.",
        "sms_total_carrier_fee": "Portion of the total cost that goes to the carrier.",
        "sms_iso_country_code": "ISO country code for the destination of the SMS.",
        "sms_carrier_name": "Name of the carrier that delivered the SMS message.",
        "sms_message_encoding": "Character encoding used for the SMS message.",
        "sms_origination_phone_number": "Phone number that sent the SMS message.",
        "feedback_reason": "Pinpoint failure reason when an SMS message cannot be delivered.",
    },
    "organisation": {
        "id": "Unique identifier for the organisation.",
        "name": "Name of the organisation.",
        "active": "Indicates whether the organisation is currently active in the system.",
        "created_at": "Date and time when the organisation record was created.",
        "updated_at": "Date and time when the organisation record was last updated.",
        "email_branding_id": "Email branding configuration used by this organisation.",
        "agreement_signed": "Indicates whether the organisation has signed the service agreement.",
        "agreement_signed_at": "Date and time when the service agreement was signed.",
        "agreement_signed_by_id": "Foreign key reference to the user who signed the service agreement.",
        "agreement_signed_version": "Version number of the service agreement that was signed",
        "crown": "Indicates whether this is a Crown Corporation.",
        "organisation_type": "Type of the organisation.",
        "default_branding_is_french": "Indicates whether the default branding for this organisation",
    },
    "permissions": {
        "id": "Unique identifier for the permission.",
        "service_id": "Foreign key reference to the service this permission applies to.",
        "user_id": "Foreign key reference to the user the permission has been granted to.",
        "permission": "The permission that has been granted.",
        "created_at": "Date and time when the permission was assigned.",
    },
    "services": {
        "id": "Unique identifier for the service.",
        "name": "Name of the service.",
        "created_at": "Date and time when the service was created.",
        "updated_at": "Date and time when the service was last updated.",
        "active": "Indicates whether the service is currently active.",
        "message_limit": "Maximum number of messages this service can send.",
        "restricted": "Indicates if this is a trial service.",
        "email_from": "Email address that appears in the 'From' field when sending email notifications.",
        "created_by_id": "Identifier of the user who created this service.",
        "version": "Current version of the service configuration.",
        "research_mode": "Indicates if this service is in research mode.",
        "organisation_type": "Type of organisation this service is classified as.",
        "prefix_sms": "Whether SMS messages should include a prefix identifying the service.",
        "crown": "Indicates if this service is operated by a Crown Corporation.",
        "rate_limit": "Maximum number of notifications the service can send per time unit.",
        "consent_to_research": "Whether the service has consented to being included in research studies.",
        "volume_email": "Anticipated volume of email notifications for this service.",
        "volume_sms": "Anticipated volume of SMS notifications for this service.",
        "count_as_live": "Whether this service should be counted as a live production service.",
        "go_live_at": "Date and time when this service went live.",
        "go_live_user_id": "Identifier of the user who requested the service to go live.",
        "organisation_id": "Reference to the organisation that this service belongs to.",
        "sending_domain": "Domain name used for sending email notifications.",
        "default_branding_is_french": "Whether the default branding for notifications is in French.",
        "sms_daily_limit": "Maximum number of SMS messages this service can send per day.",
        "organisation_notes": "Additional notes about the organisation in relation to this service.",
        "sensitive_service": "Indicates if this service handles sensitive or protected information.",
        "email_annual_limit": "Maximum number of email notifications this service can send annually.",
        "sms_annual_limit": "Maximum number of SMS notifications this service can send annually.",
    },
    "services_history": {
        "id": "Unique identifier for the service.",
        "name": "Name of the service.",
        "created_at": "Date and time when the service was created.",
        "updated_at": "Date and time when the service was last updated.",
        "active": "Indicates whether the service is currently active.",
        "message_limit": "Maximum number of messages this service can send.",
        "restricted": "Indicates if this is a trial service.",
        "email_from": "Email address that appears in the 'From' field when sending email notifications.",
        "created_by_id": "Identifier of the user who created this service.",
        "version": "Current version of the service configuration.",
        "research_mode": "Indicates if this service is in research mode.",
        "organisation_type": "Type of organisation this service is classified as.",
        "prefix_sms": "Whether SMS messages should include a prefix identifying the service.",
        "crown": "Indicates if this service is operated by a Crown Corporation.",
        "rate_limit": "Maximum number of notifications the service can send per time unit.",
        "consent_to_research": "Whether the service has consented to being included in research studies.",
        "volume_email": "Anticipated volume of email notifications for this service.",
        "volume_sms": "Anticipated volume of SMS notifications for this service.",
        "count_as_live": "Whether this service should be counted as a live production service.",
        "go_live_at": "Date and time when this service went live.",
        "go_live_user_id": "Identifier of the user who requested the service to go live.",
        "organisation_id": "Reference to the organisation that this service belongs to.",
        "sending_domain": "Domain name used for sending email notifications.",
        "default_branding_is_french": "Whether the default branding for notifications is in French.",
        "sms_daily_limit": "Maximum number of SMS messages this service can send per day.",
        "organisation_notes": "Additional notes about the organisation in relation to this service.",
        "sensitive_service": "Indicates if this service handles sensitive or protected information.",
        "email_annual_limit": "Maximum number of email notifications this service can send annually.",
        "sms_annual_limit": "Maximum number of SMS notifications this service can send annually.",
    },
    "template_categories": {
        "id": "Unique identifier for the template category.",
        "name_en": "English name of the template category.",
        "name_fr": "French name of the template category.",
        "description_en": "English description of what this template category is used for.",
        "description_fr": "French description of what this template category is used for.",
        "sms_process_type": "Defines the processing priority of SMS templates in this category.",
        "email_process_type": "Defines the processing priority of email templates in this category.",
        "hidden": "Indicates whether this category should be hidden in the interface.",
        "created_at": "Date and time when this template category was created.",
        "updated_at": "Date and time when this template category was last updated.",
        "sms_sending_vehicle": "Defines if templates in this category use a short or long code for sending.",
    },
    "templates": {
        "id": "Unique identifier for the notification template.",
        "name": "Name of the template.",
        "template_type": "Categorization of the template (email or sms).",
        "created_at": "Date and time when the template was created.",
        "updated_at": "Date and time when the template was last modified.",
        "service_id": "Foreign key reference to the service that owns this template.",
        "created_by_id": "Foreign key reference to the user who created the template.",
        "version": "Version number of the template.",
        "archived": "Indicates whether the template has been archived and is no longer available for new notifications.",
        "process_type": "Defines the processing priority of notification sent using this template.",
        "hidden": "Indicates whether the template should be hidden in the interface.",
        "template_category_id": "Foreign key reference to the category this template belongs to.",
        "text_direction_rtl": "Indicates whether the template content should be rendered right-to-left.",
    },
    "templates_history": {
        "id": "Unique identifier for the notification template.",
        "name": "Name of the template.",
        "template_type": "Categorization of the template (email or sms).",
        "created_at": "Date and time when the template was created.",
        "updated_at": "Date and time when the template was last modified.",
        "service_id": "Foreign key reference to the service that owns this template.",
        "created_by_id": "Foreign key reference to the user who created the template.",
        "version": "Version number of the template.",
        "archived": "Indicates whether the template has been archived and is no longer available for new notifications.",
        "process_type": "Defines the processing priority of notification sent using this template.",
        "hidden": "Indicates whether the template should be hidden in the interface.",
        "template_category_id": "Foreign key reference to the category this template belongs to.",
        "text_direction_rtl": "Indicates whether the template content should be rendered right-to-left.",
    },
    "user_to_organisation": {
        "user_id": "Foreign key reference for the user linked to the organisation.",
        "organisation_id": "Foreign key reference for the organisation linked to the user.",
    },
    "user_to_service": {
        "user_id": "Foreign key reference for the user linked to the service.",
        "service_id": "Foreign key reference for the service linked to the user.",
    },
    "users": {
        "id": "Unique identifier for the user account.",
        "created_at": "Date and time when the user account was created.",
        "updated_at": "Date and time when the user account was last modified.",
        "password_changed_at": "Date and time when the user last changed their password.",
        "logged_in_at": "Date and time of the user's most recent successful login.",
        "failed_login_count": "Number of consecutive failed login attempts for this user account.",
        "state": "Current status of the user account (active, inactive, pending).",
        "platform_admin": "Indicates whether the user has system-wide administrator privileges.",
        "auth_type": "2FA authentication method used by this user (email_auth, sms_auth).",
        "blocked": "Indicates whether the user is currently blocked from accessing the system.",
        "password_expired": "Indicates whether the user's password has expired and needs to be reset.",
    },
}

def upgrade():
    for table, cols in COMMENTS.items():
        for col, comment in cols.items():
            op.alter_column(table, col, comment=comment)
    

def downgrade():
    for table, cols in COMMENTS.items():
        for col in cols.keys():
            op.alter_column(table, col, comment=None)
