version: '3'

services:
  dev:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    entrypoint: notify-dev-entrypoint.sh
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:chummy@db/notification_api
    volumes:
      - ..:/workspace:cached   
    command: sleep infinity
    ports: 
      - 8000:8000
      - 8001:8001
    links: 
      - db

  db:
    image: postgres:11.2
    volumes:
    - ./initdb:/docker-entrypoint-initdb.d
    restart: always
    command:
      - "postgres"
      - "-c"
      - "listen_addresses=*"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: chummy
      POSTGRES_HOST_AUTH_METHOD: trust
    expose:
      - "5432" 
    ports:
      - "5432:5432"
