version: '3'

services:
  dev:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    entrypoint: dev-notif-entrypoint.sh
    volumes:
      - ..:/workspace:cached   
    command: sleep infinity
    ports: 
      - 8000:8000
      - 8001:8001
    links: 
      - db

  db:
    build:
      context: .
      dockerfile: DbDockerfile
    restart: always
    command:
      - "postgres"
      - "-c"
      - "listen_addresses=*"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: chummy@@
      POSTGRES_HOST_AUTH_METHOD: trust
    expose:
      - "5432" 
    ports:
      - "5432:5432"
