version: '3'

services:
  dev:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached   
    command: sleep infinity
    ports: 
      - 8000:8000
      - 8001:8001
    links: 
      - db

  db:
    image: postgres:13.0
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: chummy@@
