version: '3'

services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:chummy@db/notification_api
      SQLALCHEMY_DATABASE_TEST_URI: postgresql://postgres:chummy@db/test_notification_api
      REDIS_URL: redis://redis:6380
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    ports:
      - 8000:8000
      - 8001:8001
      - 6011:6011
    links:
      - db

  db:
    image: postgres:11.17-bullseye@sha256:c4272e8dfc4144bfd03ee6df90ac769330976c80662e7c351996068d9c0f8ee7
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    restart: always
    command:
      - "postgres"
      - "-c"
      - "listen_addresses=*"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: chummy
      POSTGRES_HOST_AUTH_METHOD: trust
    expose:
      - "5432"
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2@sha256:9360de4b60a90ad2ebf9da98e265cd7f1155f25397c4c6344646b48ed09d9424
    restart: always
    command: redis-server --port 6380
    ports:
      - "6380:6380"
    expose:
      - "6380"
