version: '3'

services:
  notify-api:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:chummy@db/notification_api
      SQLALCHEMY_DATABASE_TEST_URI: postgresql://postgres:chummy@db/test_notification_api
      REDIS_URL: redis://redis:6380
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    ports:
      - 8000:8000
      - 8001:8001
      - 6011:6011
    links:
      - db
    expose:
      - "6011"
    networks:
      - notify-network

  db:
    image: postgres:11.22-bullseye@sha256:c886a3236b3d11abc302e64309186c90a69b49e53ccff23fd8c8b057b5b4bce9
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    restart: always
    command:
      - "postgres"
      - "-c"
      - "listen_addresses=*"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: chummy
      POSTGRES_HOST_AUTH_METHOD: trust
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - notify-network

  redis:
    image: redis:6.2@sha256:7919fdd5300e7abf7ae95919e6f144b37c55df16553302dbbcc7495a5aa0c079
    restart: always
    command: redis-server --port 6380
    ports:
      - "6380:6380"
    expose:
      - "6380"
    networks:
      - notify-network

networks:
  notify-network:
    name:   notify-network
    driver: bridge
