version: '3'

services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:chummy@db/notification_api
      SQLALCHEMY_DATABASE_TEST_URI: postgresql://postgres:chummy@db/test_notification_api
      REDIS_URL: redis://redis:6380
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    ports:
      - 8000:8000
      - 8001:8001
      - 6011:6011
    links:
      - db

  db:
    image: postgres:11.22-bullseye@sha256:c886a3236b3d11abc302e64309186c90a69b49e53ccff23fd8c8b057b5b4bce9
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    restart: always
    command:
      - "postgres"
      - "-c"
      - "listen_addresses=*"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: chummy
      POSTGRES_HOST_AUTH_METHOD: trust
    expose:
      - "5432"
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2@sha256:bd84e1c73f6d7120282d455b8506220f668cad4544e11e63c2376605dc2d4141
    restart: always
    command: redis-server --port 6380
    ports:
      - "6380:6380"
    expose:
      - "6380"
