#!/usr/bin/env python3
"""
Generate OpenAPI spec YAML files from a Jinja2 template and CSV translations.

The English file is generated by rendering the template with a pass-through
translation function.  Other languages are generated by loading the corresponding
<lang>.csv file from openapi/translations/ and using it as the lookup table.

Usage:
    python scripts/generate_openapi.py           # generates both EN and FR
    python scripts/generate_openapi.py en        # generates EN only
    python scripts/generate_openapi.py fr        # generates FR only
    python scripts/generate_openapi.py en fr     # explicit list of languages

Adding a new language:
    1. Create openapi/translations/<lang>.csv with columns: english,french
    2. Run:  python scripts/generate_openapi.py <lang>
"""

import csv
import sys
from pathlib import Path

import jinja2

OPENAPI_DIR = Path(__file__).parent.parent / "openapi"
TEMPLATE_FILE = OPENAPI_DIR / "v2-notifications-api.yaml.j2"
TRANSLATIONS_DIR = OPENAPI_DIR / "translations"


def load_translations(lang: str) -> dict[str, str]:
    """Load a <lang>.csv translation table and return a dict of {english: translated}."""
    csv_path = TRANSLATIONS_DIR / f"{lang}.csv"
    if not csv_path.exists():
        raise FileNotFoundError(
            f"No translation file found for language '{lang}': {csv_path}\n"
            f"Create {csv_path} with columns 'english,french' to add this language."
        )
    table: dict[str, str] = {}
    with open(csv_path, newline="", encoding="utf-8") as f:
        reader = csv.reader(f)
        next(reader)  # skip header row (english,french)
        for row in reader:
            if len(row) >= 2:
                table[row[0]] = row[1]
    return table


def generate(lang: str) -> None:
    """Render the Jinja2 template for *lang* and write the output YAML file."""
    env = jinja2.Environment(
        loader=jinja2.FileSystemLoader(str(OPENAPI_DIR)),
        keep_trailing_newline=True,
        autoescape=False,
        undefined=jinja2.Undefined,
    )

    if lang == "en":
        # English is the base language — t() is a pass-through.
        table: dict[str, str] = {}
    else:
        table = load_translations(lang)

    # t(key) returns the translated string if one exists, otherwise the key
    # itself (graceful fallback: untranslated strings stay in English).
    env.globals["t"] = lambda key: table.get(key, key)

    template = env.get_template(TEMPLATE_FILE.name)
    output = template.render()

    out_file = OPENAPI_DIR / f"v2-notifications-api-{lang}.yaml"
    out_file.write_text(output, encoding="utf-8")
    print(f"Generated: {out_file}")


def main() -> None:
    langs = sys.argv[1:] if len(sys.argv) > 1 else ["en", "fr"]
    for lang in langs:
        generate(lang)


if __name__ == "__main__":
    main()
