steps:  
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/statsd:$SHORT_SHA',
        '-t',
        'gcr.io/$PROJECT_ID/statsd:latest',
        '-f',
        'ci/Dockerfile.statsD',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/statsd:$SHORT_SHA']
images:
  - 'gcr.io/$PROJECT_ID/statsd:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/statsd:latest'