steps:  
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/testing-env:abcd',
        '-t',
        'gcr.io/$PROJECT_ID/testing-env:latest',
        '-f',
        'ci/Dockerfile.test',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/testing-env:abcd']
images:
  - 'gcr.io/$PROJECT_ID/testing-env:abcd'
  - 'gcr.io/$PROJECT_ID/testing-env:latest'