FROM 171875617347.dkr.ecr.us-gov-west-1.amazonaws.com/datadog/agent:latest

RUN apk update && apk add --no-cache ca-certificates && rm -rf /var/cache/apk/*
COPY ./certs/VA-Internal-S2-RCA1-v1.crt /usr/local/share/ca-certificates/VA-Internal-S2-RCA1-v1.crt
RUN update-ca-certificates

ENV REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
