FROM python:3.6-alpine

ENV PYTHONDONTWRITEBYTECODE 1
RUN apk add --no-cache bash build-base git gcc musl-dev postgresql-dev g++ make libffi-dev libmagic libcurl python3-dev openssl-dev curl-dev && rm -rf /var/cache/apk/*
RUN python -m pip install wheel
RUN set -ex && mkdir /app

COPY requirements_for_test.txt /app/requirements_for_test.txt
COPY requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip install -r requirements_for_test.txt --use-deprecated=legacy-resolver

COPY . /app
CMD ["sh", "-c", "make test"]