FROM python:3.12-slim@sha256:2b0079146a74e23bf4ae8f6a28e1b484c6292f6fb904cbb51825b4a19812fcd8

ENV PYTHONPATH "${PYTHONPATH}:/opt/python/lib/python3.12/site-packages"
ENV PYTHONDONTWRITEBYTECODE 1
ENV TASK_ROOT /app
ENV APP_VENV="${TASK_ROOT}/.venv"
ENV POETRY_HOME="/opt/poetry"
ENV POETRY_VERSION="1.7.1"
ENV POETRY_VIRTUALENVS_CREATE="false"
ENV PATH="${APP_VENV}/bin:${POETRY_HOME}/bin:$PATH"

RUN apt-get update
RUN apt-get install -y bash git libtool  autoconf automake gcc  g++ make libffi-dev unzip

RUN mkdir -p ${TASK_ROOT}
WORKDIR ${TASK_ROOT}

# Install poetry and isolate it in it's own venv
RUN python -m venv ${POETRY_HOME} \
    && ${POETRY_HOME}/bin/pip3 install poetry==${POETRY_VERSION}

COPY pyproject.toml poetry.lock ${TASK_ROOT}/

RUN python -m venv ${APP_VENV} \
    && . ${APP_VENV}/bin/activate \
    && poetry install \
    && poetry add awslambdaric newrelic-lambda wheel

COPY . ${TASK_ROOT}/

RUN . ${APP_VENV}/bin/activate \
    && make generate-version-file

ENV PORT=6011

ARG GIT_SHA
ENV GIT_SHA ${GIT_SHA}

# (Optional) Add Lambda Runtime Interface Emulator and use a script in the ENTRYPOINT for simpler local runs
ADD https://github.com/aws/aws-lambda-runtime-interface-emulator/releases/latest/download/aws-lambda-rie /usr/bin/aws-lambda-rie
COPY bin/entry.sh /
COPY bin/sync_lambda_envs.sh /
RUN chmod 755 /usr/bin/aws-lambda-rie /entry.sh /sync_lambda_envs.sh

# New Relic lambda layer
RUN unzip newrelic-layer.zip -d /opt && rm newrelic-layer.zip

ENTRYPOINT [ "/entry.sh" ]

# Launch the New Relic lambda wrapper which will then launch the app
# handler defined in the NEW_RELIC_LAMBDA_HANDLER environment variable
CMD [ "newrelic_lambda_wrapper.handler" ]