# Python 3.8 is supported until 14 October 2024.
FROM python:3.8-slim

RUN apt-get update && apt-get install -y make

ENV PYTHONDONTWRITEBYTECODE 1
RUN set -ex && mkdir /app

COPY requirements_for_user_flows.txt /app/requirements_for_user_flows.txt
WORKDIR /app
RUN pip install -r requirements_for_user_flows.txt \
  && rm requirements_for_user_flows.txt

COPY . /app
CMD ["sh", "-c", "make user_flows"]
