name: 'Builds and Push Artifacts'
description: 'Builds and pushes a Docker image, S3 env vars file, and dispatches a Twistlock workflow'
inputs:
  environment:
    required: true
    default: "dev"
    type: string
  ref:
    description: 'Git reference (commit SHA, branch, or tag) to build'
    required: true
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true
  role-to-assume:
    description: 'AWS role to assume'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}

    - name: Configure VAEC AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4.0.2
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: us-gov-west-1
        role-to-assume: ${{ inputs.role-to-assume }}
        role-skip-session-tagging: true
        role-duration-seconds: 900

    - name: Upload Env File to S3
      shell: bash
      run: |
        aws s3 cp cd/application-deployment/${{ inputs.environment }}/${{ inputs.environment }}.env s3://vanotify-environment-variables-${{ inputs.environment }}/

    - name: Login to VAEC ECR
      id: login-ecr-vaec
      uses: aws-actions/amazon-ecr-login@v2
      with:
        mask-password: 'true'

    - name: Docker Build
      uses: docker/build-push-action@v6
      with:
        file: ci/Dockerfile
        context: .
        push: true
        tags: ${{ steps.login-ecr-vaec.outputs.registry }}/notification_api:${{ inputs.ref }}_${{ inputs.environment }}

    - name: Dispatch Twistlock Workflow
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh workflow run -r main -F image-tag=${{ inputs.ref }}_${{ inputs.environment }} twistlock.yml
