name: AI Code Review

on:
  push:
    branches-ignore:
      - main

jobs:
  ai_code_review:
    if: contains(github.event.head_commit.message, '[review]')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: AI Code Review
      uses: cds-snc/cds-ai-codereviewer@main
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        OPENAI_API_MODEL: ${{ vars.OPENAI_API_MODEL }}
        OPENAI_API_VERSION: ${{ vars.OPENAI_API_VERSION }}
        OPENAI_BASE_URL: ${{ vars.OPENAI_BASE_URL }}
        exclude: "*lock*,.env,**/*.conf,**/*.ini,**/node_modules/**"
        include: "**/*.cfg,**/*.md,**/*.py,**/*.js,**/*.json,**/*.sh,**/*.yml,**/*.yaml"
