name: Create Release Notes

on: 
  workflow_call:
    inputs:
      previous_version:
        required: true
        type: string

jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Create Release Notes
        uses: actions/github-script@v7
        env:
          previousVersion: ${{ inputs.previous_version }}
        with:
          github-token: ${{ secrets.VAR_PAT }}
          script: |
            const createReleaseNotes = require('.github/scripts/createReleaseNotes.js');
            createReleaseNotes({github, context, core});

