name: Create Release Notes

on: 
  workflow_call:
    inputs:
      previousVersion:
        required: true
        type: string
    outputs:
      draftReleaseReference:
        description: 'This value is the id that will be used when actually publishing this release notes'
        value: ${{ jobs.create-release-notes.outputs.draftReleaseReference }}

jobs:
  create-release-notes:
    runs-on: ${{ vars.RUNS_ON }}
    outputs:
      draftReleaseReference: ${{ steps.create_notes.outputs.draftReleaseReference }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Create Release Notes
        id: create_notes
        uses: actions/github-script@v7
        env:
          previousVersion: ${{ inputs.previousVersion }}
        with:
          github-token: ${{ secrets.VAR_PAT }}
          # This script outputs draftReleaseReference for publish-release-notes.yml
          script: |
            const createReleaseNotes = require('.github/scripts/createReleaseNotes.js');
            createReleaseNotes({github, context, core});

