name: Cypress tests

on:
  push:

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11.17-bullseye
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: chummy
          POSTGRES_DB: notification_api
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis:6.2@sha256:9e75c88539241ad7f61bc9c39ea4913b354064b8a75ca5fc40e1cef41b645bc0
        ports:
        - 6379:6379

    steps:
    - name: Install libcurl
      run: sudo apt-get update && sudo apt-get install libssl-dev libcurl4-openssl-dev

    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Set up Python 3.12
      uses: actions/setup-python@b64ffcaf5b410884ad320a9cfac8866006a109aa # v4.8.0
      with:
        python-version: '3.12'

    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    - uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install poetry
      env:
        POETRY_VERSION: 1.3.2
      run: pip install poetry==${POETRY_VERSION} && poetry --version

    - name: Check poetry.lock aligns with pyproject.toml
      run: poetry lock --check

    - name: Install requirements
      run: poetry install --with test

    - name: Get python version
      run: |
        python_version=$(python  -V | cut -d' ' -f2)
        echo "python_version=${python_version}" >> $GITHUB_ENV
    
    - name: Make version file
      run: |
        printf '__commit_sha__ = "09cfe03100443fb9071bba88d5c8775ff54a9ebc"\n__time__ = "2022-07-25:15:11:05"\n' > version.py
        cp version.py "${{ github.workspace }}/app/"

    - name: Setup .env
      run: |
        echo 'NOTIFICATION_QUEUE_PREFIX=api-pr-notification-canada-ca' > .env
        echo 'AWS_ACCESS_KEY_ID=${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}' >> .env
        echo 'AWS_SECRET_ACCESS_KEY=${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}' >> .env
        echo 'AWS_REGION=ca-central-1' >> .env
        echo 'ASSET_DOMAIN=example.com' >> .env
        echo 'ASSET_UPLOAD_BUCKET_NAME=not-a-real-secret' >> .env
        echo 'CSV_UPLOAD_BUCKET_NAME=notification-canada-ca-staging-csv-upload' >> .env
        echo 'DOCUMENTS_BUCKET=not-a-real-secret' >> .env
        echo 'NOTIFY_EMAIL_DOMAIN=staging.notification.cdssandbox.xyz' >> .env
        echo 'ADMIN_CLIENT_SECRET=local_app' >> .env
        echo 'REDIS_URL=redis://redis:6379' >> .env
        echo 'REDIS_PUBLISH_URL=redis://redis:6379' >> .env
        echo 'SQLALCHEMY_DATABASE_URI=postgresql://postgres:chummy@localhost:5432/notification_api' >> .env
        echo 'SQLALCHEMY_DATABASE_READER_URI=postgresql://postgres:chummy@localhost:5432/notification_api' >> .env
        echo 'DOCUMENT_DOWNLOAD_API_HOST=http://host.docker.internal:7000' >> .env
        echo 'FF_REDIS_BATCH_SAVING=true' >> .env
        echo 'FF_BATCH_INSERTION=true' >> .env
        echo 'REDIS_ENABLED=true' >> .env
        echo 'FF_CLOUDWATCH_METRICS_ENABLED=false' >> .env
        echo 'FF_SPIKE_SMS_DAILY_LIMIT=true' >> .env
        echo 'FRESH_DESK_ENABLED=false' >> .env
        echo 'SECRET_KEY=${{ secrets.SECRET_KEY }}' >> .env
        echo 'DANGEROUS_SALT=${{ secrets.DANGEROUS_SALT }}' >> .env
        echo 'NOTIFY_ENVIRONMENT=test' >> .env
        echo 'FLASK_APP=application.py' >> .env
        echo 'FLASK_DEBUG=true' >> .env
        echo 'WERKZEUG_DEBUG_PIN=off' >> .env
        pwd

    - name: prep db and run notify api
      run: |
        poetry run flask db upgrade
        poetry run make run &

    - name: Write the cypress.env.json file
      run: |
        echo '${{ secrets.CYPRESS_ENV_JSON }}' > tests_cypress/cypress.env.json 

    - name: Checkout frontend repository
      uses: actions/checkout@v3
      with:
        repository: cds-snc/notification-admin
        path: frontend

    - uses: actions/setup-python@b64ffcaf5b410884ad320a9cfac8866006a109aa # v4.8.0
      with:
        python-version: '3.12'

    - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
      with:
        node-version: '16.x'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    # - name: Install poetry
    #   env:
    #     POETRY_VERSION: "1.7.1"
    #   run: pip install poetry==${POETRY_VERSION} poetry-plugin-sort && poetry --version

    # - name: Install requirements
    #   run: poetry install --with test

    - name: Install frontend dependencies
      working-directory: frontend
      run: npm ci

    - name: Configure frontend environment
      working-directory: frontend
      run: |
        cp ${{ github.workspace }}/.env .env

    - name: Make version file
      run: |
        printf '__commit_sha__ = "09cfe03100443fb9071bba88d5c8775ff54a9ebc"\n__time__ = "2022-07-25:15:11:05"\n' > version.py
        cp version.py "${{ github.workspace }}/app/"

    - name: Build and start frontend
      working-directory: frontend
      run: |
        cd ${{ github.workspace }}/frontend
        python -m poetry install
        make run-dev &

    - name: Run cypress tests
      uses: cypress-io/github-action@d79d2d530a66e641eb4a5f227e13bc985c60b964 # v4.2.2
      env:
        CYPRESS_BASE_URL: http://localhost:6012
      with:
        record: false
        build: npx cypress info
        working-directory: tests_cypress
        spec: cypress/e2e/api/email_notifications.cy.js
