name: Deploy Lambdas to Env
run-name: "Deploy Lambdas to ${{ inputs.environment }}"

on:
  workflow_dispatch:
    inputs:
      ref:
        description: Branch to deploy
        required: true
        default: master
      environment:
        type: choice
        description: Environment to deploy
        default: dev
        options:
          - dev
          - perf
          - staging
          - prod
      lambda:
        type: choice
        description: Make a choice
        required: true
        options:
          - All
          - VetTextIncomingForwarder
          - SESCallback
          - TwoWaySMS
          - PinPointCallback
          - PinPointInboundSMS
          - ProfileOptInOut
          - ProfileRemoveOldOptOuts
          - NightBigQueryUpload
          - NightBillingBQUpload
          - DeliveryStatusProcessor

jobs:
  setup_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Env Values
        run: |
          echo "The branch/tag is ${{ inputs.ref }}"
          echo "The Lambda Deployment is ${{ inputs.lambda }}"

  build_deploy_lambda:
    needs: [setup_job]
    uses: ./.github/workflows/lambda-functions.yml
    with:
      environment: ${{ inputs.environment }}
      ref: ${{ inputs.ref }}
      lambdaName: ${{ inputs.lambda }}
    secrets: inherit
