name: Running Tests

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch or Commit"
        type: string
        required: true
  workflow_call:
    inputs:
      ref:
        description: "Branch or Commit"
        type: string
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Run tests using docker-compose
        run: |
          # Build images, start containers, and run tests.
          docker compose -f ci/docker-compose-ci.yml up --build --abort-on-container-exit
          # Tear down containers after tests complete
          docker compose -f ci/docker-compose-ci.yml down

  code-scan:
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: make check-vulnerabilities

  dependency-scan:
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: make check-dependencies