name: Running Tests

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch or Commit"
        type: string
        required: true
  workflow_call:
    inputs:
      ref:
        description: "Branch or Commit"
        type: string
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Run tests using docker-compose
        run: |
          # Start DB container
          docker compose -f ci/docker-compose-ci.yml up -d db
          # Run test container
          docker compose -f ci/docker-compose-ci.yml run --rm test
          # Stop test container (it should already be stopped due to --rm, but just in case)
          docker compose -f ci/docker-compose-ci.yml stop test

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.VAEC_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.VAEC_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-gov-west-1
          role-to-assume: ${{ secrets.VAEC_DEPLOY_ROLE }}
          role-skip-session-tagging: true
          role-duration-seconds: 1800

      - name: Dump and upload schema
        run: |
          docker exec ci-db-1 pg_dump -U postgres -s -d notification_api > napi-schema.sql
          aws s3 cp napi-schema.sql s3://vanotify-environment-variables-dev/notification-api/schemas/napi-schema.sql
          docker compose -f ci/docker-compose-ci.yml down

  code-scan:
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: make check-vulnerabilities

  dependency-scan:
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: make check-dependencies