name: Running Tests

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch or Commit"
        type: string
        required: true
  workflow_call:
    inputs:
      ref:
        description: "Branch or Commit"
        type: string
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      # Caching requires 3 steps here
      # 1. Set up Docker Buildx - according to https://docs.docker.com/build/cache/backends/gha/,
      #    the standard Docker driver is not supported for caching. Setting up buildx is necessary.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          version: latest  # Ensure we get version >= 0.21.0 for new cache service
        
      # 2. Set up GitHub Actions Runtime
      #    This is required to set up the runtime and expose ${ACTIONS_RESULTS_URL}, which is used by buildx.
      #    Referenced here: https://docs.docker.com/build/cache/backends/gha/#authentication
      - name: Set up GitHub Actions Runtime
        uses: crazy-max/ghaction-github-runtime@3cb05d89e1f492524af3d41a1c98c83bc3025124 # v3.1.0 -- pinned to avoid breaking changes

      # 3. Compose build (with cache)
      #    This is the actual build step that uses the cache.
      - name: Compose build (with cache)
        run: |
          docker compose \
            -f ci/docker-compose-ci.yml \
            build --builder "${BUILDX_BUILDER}"

      - name: Run tests using docker-compose
        run: |
          # Start DB container
          docker compose -f ci/docker-compose-ci.yml up -d db redis
          # Run test container
          docker compose -f ci/docker-compose-ci.yml run --rm test
          # Stop test container (it should already be stopped due to --rm, but just in case)
          docker compose -f ci/docker-compose-ci.yml stop test

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.VAEC_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.VAEC_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-gov-west-1
          role-to-assume: ${{ secrets.VAEC_DEPLOY_ROLE }}
          role-skip-session-tagging: true
          role-duration-seconds: 1800

      - name: Dump and upload schema
        run: |
          docker exec ci-db-1 pg_dump -U postgres -d notification_api > napi-schema.sql
          aws s3 cp napi-schema.sql s3://vanotify-environment-variables-dev/notification-api/schemas/napi-schema.sql
          docker compose -f ci/docker-compose-ci.yml down

  code-scan:
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: make check-vulnerabilities
