name: Docker Test Workflow

on:
  push:
    branches:
      - helm-tagging5

jobs:
  update-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Docker Tag
        run: echo "DOCKER_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV
        env:
          GITHUB_SHA: ${{ github.sha }}
  
      - name: Update images in staging (Helm)
        run: |
          curl -L \
          -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.MANIFESTS_WORKFLOW_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/cds-snc/notification-manifests/dispatches \
            -d '{"event_type":"update-docker-image","client_payload":{"component":"API","docker_tag":"${{ env.DOCKER_TAG }}"}}'