name: Performance Build and Deploy

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Git commit SHA (full-length), tag, or Branch name for its latest commit."
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_REPOSITORY: "notification_api_perf"
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Set image tag
        id: set-image-tag
        run: |
          echo "::set-output name=image-tag::$(git rev-parse HEAD)"

      - name: Build docker image
        env:
          IMAGE_TAG: ${{ steps.set-image-tag.outputs.image-tag }}
        run: |
          docker build -t $IMAGE_REPOSITORY:$IMAGE_TAG -f ci/Dockerfile .

      - name: Configure VAEC AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.VAEC_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.VAEC_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-gov-west-1
          role-to-assume: ${{ secrets.VAEC_DEPLOY_ROLE }}
          role-skip-session-tagging: true
          role-duration-seconds: 900

      - name: Login to VAEC ECR
        id: login-ecr-vaec
        uses: aws-actions/amazon-ecr-login@v1

      - name: Publish to VAEC ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr-vaec.outputs.registry }}
          IMAGE_TAG: ${{ steps.set-image-tag.outputs.image-tag }}
        run: |
          docker tag $IMAGE_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$IMAGE_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$IMAGE_REPOSITORY:$IMAGE_TAG

      - name: Perform twistlock scan
        uses: ./.github/actions/run-commands-on-ec2
        env:
          ECR_REGISTRY: ${{ steps.login-ecr-vaec.outputs.registry }}
          IMAGE_TAG: ${{ steps.set-image-tag.outputs.image-tag }}
        with:
          instance-id-ssm-parameter-path: /utility/twistlock/instance
          commands: >-
            "aws --region us-gov-west-1 ecr get-login-password | docker login --username AWS --password-stdin '"$ECR_REGISTRY"' 2>/dev/null",
            "docker pull '"$ECR_REGISTRY"'/'"$IMAGE_REPOSITORY"':'"$IMAGE_TAG"' 1>/dev/null",
            "docker logout '"$ECR_REGISTRY"'",
            "export TWISTLOCK_PASSWORD=$(aws --region us-gov-west-1 ssm get-parameter --name /utility/twistlock/vanotify-ci-user-password --with-decryption | jq '.Parameter.Value' -r)",
            "twistcli images scan --project VaNotify --address https://twistlock.devops.va.gov --user vanotify-ci-user '"$ECR_REGISTRY"'/'"$IMAGE_REPOSITORY"':'"$IMAGE_TAG"'",
            "STATUS_CODE=$?",
            "docker image prune -a -f 1>/dev/null",
            "exit $STATUS_CODE"

  start-vaec-perf-deployment:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - uses: actions/github-script@v4.1
        with:
          github-token: ${{secrets.GH_ACCESS_TOKEN}}
          script: |
            const payload = {"imageRepository": "notification_api_perf"}
            github.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.payload.inputs.ref,
              environment: 'perf',
              required_contexts: [],
              auto_merge: false,
              payload: payload,
            });