name: CD Pipeline PR Labels and Semver bump Summary

on: 
  workflow_call:

permissions:
  contents: write

jobs:
  check-pr-sem:
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - uses: actions/checkout@v5
      - name: PR Label Semver
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.VAR_PAT }}
          script: |
            const path = '.github/scripts/prLabelSemver.js';
            const prLabelSemver = require(path);
            prLabelSemver({github, context, core});

