name: Test docker builds on pull request

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build k8s image

    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

      - name: Build k8s image
        run: |
          docker buildx build \
            --build-arg GIT_SHA=${GITHUB_SHA::7} \
            -f ci/Dockerfile \
            .
