name: CD Pipeline Pre Tag Summary

on: 
  workflow_call:

jobs:
  pre-tag-summary:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Pre Tag Summary
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.VAR_PAT }}
          script: |
            const path = '.github/scripts/preTagSummary.js';
            const preTagSummary = require(path);
            preTagSummary({github, context, core});

