name: Pre-release to Staging
on:
  release:
    types: [published]

jobs:
  setup-release:
    runs-on: ubuntu-latest
    outputs:
      git-tag: ${{ steps.tag.outputs.version }}
    steps:
      - name: Init
        run: |
          echo Deploy starting
          # this allows for blame
          echo ${{ github.actor }}
      - name: Check release and env values
        run: |
          echo "Release tag: ${{ github.event.release.tag_name }}"	          
          echo "Release name: ${{ github.event.release.name }}"
          echo "is a prerelease? (github.event.release.prerelease): ${{ github.event.release.prerelease }}"

  pre-release:
    needs: [setup-release]
    uses: ./.github/workflows/release.yml
    with:
      environment: "staging"
      git-tag: "${{ github.event.release.tag_name }}"
    secrets: inherit
