name: Production Deployment Trigger

# This is now to deploy specifically to production using an existing container tag up in ECR.
# To deploy, go into ECR and find the tag SHA or hash that you wish to deploy.
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "This is now to deploy specifically to production using an existing container tag up in ECR. "
        required: true
        default: "prod"
      ref:
        description: "Docker tag (can be a commit SHA)."
        required: true

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Choose environment
        id: choose-environment
        uses: actions/github-script@v6
        with:
          script: |
            const mapEventToEnvironment = () => {
            if (context.payload.inputs.environment == 'prod') return { "environment": context.payload.inputs.environment, "ref": context.payload.inputs.ref };
            };
            const { environment, ref } = mapEventToEnvironment();
            core.setOutput('environment', environment);
            core.setOutput('ref', ref);

      - name: Start VAEC deployment
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GH_ACCESS_TOKEN}}
          script: |
            github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: '${{ steps.choose-environment.outputs.ref }}',
              environment: '${{ steps.choose-environment.outputs.environment }}',
              required_contexts: [],
              auto_merge: false,
            });
