name: Release
on:
  workflow_call:
    inputs:
      environment: 
        required: true
        type: string
      git-tag:
        required: true
        type: string

jobs:
  run-build:
    uses: ./.github/workflows/build.yml
    with:
      environment: "${{ inputs.environment }}"
      ref: "${{ inputs.git-tag }}"
    secrets: inherit

  run-lambda-deploy:
    uses: ./.github/workflows/lambda-functions.yml
    with:
      environment: "${{ inputs.environment }}"
      ref: "${{ inputs.git-tag }}"
      lambdaName: "All"
    secrets: inherit

  run-deployment:
    needs: [run-build]
    uses: ./.github/workflows/deployment.yml
    with:
      environment: "${{ inputs.environment }}"
      ref: "${{ inputs.git-tag }}"
    secrets: inherit
