name: Run make freeze-requirements and commit results

on:
  push:
    # branches:
    #   - "renovate/*"
    paths:
      - "requirements-app.txt"
      - "requirements_for_test.txt"

jobs:
  freeze-requirements:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Install virutalenv
      #   run: pip3 install virtualenv

      # - name: Install libcurl
      #   run: sudo apt-get update && sudo apt-get install libssl-dev libcurl4-openssl-dev

      # - name: Generate requirements.txt
      #   run: make freeze-requirements

      - name: Commit changes back
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"
          touch _$RANDOM
          git add -A
          git commit -m "Run make freeze-requirements" -a
          git push https://andrewleith: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@github.com/${GITHUB_REPOSITORY}.git
      
      # - name: Extract branch name
      #   run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      #   id: extract_branch

      - name: Trigger test workflow again
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ PAT_ANDREW }}" \
            https://api.github.com/repos/cds-snc/notification-api/actions/workflows/test.yaml/dispatches \
            -d '{"ref":"experiment/renovate-github-actions"}'
