name: Call Notification API QA Regression Tests
# Note:
# The notification-api-qa repo has a workflow that controls which regression is run for which environment.
#   For dev, perf and staging, the full regression is run.
#   For prod, only a smoke test is run.
# Changes to which type of testing is done thus must be made in that repository.

permissions:
  contents: read
  actions: write

on: 
  workflow_call:
    inputs:
      environment:
        description: 'Notification-api deployment environment to test (dev|perf|staging|prod)'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        description: 'Notification-api deployment environment to test (dev|perf|staging|prod)'
        required: true
        type: string

jobs:
  trigger-regression-tests:
    name: "Run regression for ${{ inputs.environment }}"
    runs-on: ${{ vars.RUNS_ON }}
    environment: ${{ inputs.environment }}
    steps:
    - uses: actions/checkout@v4

    - name: Trigger Regression Workflow
      uses: actions/github-script@v7
      env:
        ENVIRONMENT: ${{ inputs.environment }}
      with:
        github-token: ${{ secrets.DISPATCH_PAT }}
        script: |
          const path = '.github/scripts/trigger-regression.js';
          const triggerAndWait = require(path);
          triggerAndWait({github, context, core});
