on: push
name: Continuous Integration
jobs:
  build:
    name: seekret-scanning
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
    - name: docker://cdssnc/seekret-github-action
      uses: docker://cdssnc/seekret-github-action@sha256:0aee6df949373ef6df26d35f6207b56f897ddd1caa030646d7421b0afb717665
