name: Shellcheck
on:
  push:
    paths:
      - "**/*.sh"

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
    - name: Shellcheck
      run: |
        .github/workflows/scripts/run-shellcheck.sh
