name: test actions
on:
  workflow_dispatch:
    inputs:
      ref:
        description: Branch to deploy
        required: true
        default: master
      action:
        type: choice
        description: Choose which actions to test
        required: true
        options:
          - All
          - codeql
          - load-test-email-delivery-time
          - load-test-sms-response-time
          - update-cached-image
          - update-datadog-image

jobs:

  build:
    if: ${{ (inputs.action == 'build') || (inputs.action == 'All') }}
    uses: ./.github/workflows/build.yml
    with:
      environment: "dev"
      ref: ${{ inputs.ref }}
      lambdaName: ${{ inputs.choice }}
    secrets: inherit

  #codeql:
    #if: ${{ (inputs.action == 'codeql') || (inputs.action == 'All') }}
    #uses: ./.github/workflows/codeql.yml

