name: test actions
on:
  workflow_dispatch:
    inputs:
      ref:
        description: Branch to deploy
        required: true
        default: master
      action:
        type: choice
        description: Choose which actions to test
        required: true
        options:
          - All
          - load-test-email-delivery-time
          - load-test-sms-response-time
          - update-cached-image
          - update-datadog-image

jobs:

  #build:
    #if: ${{ (inputs.action == 'build') || (inputs.action == 'All') }}
    #uses: ./.github/workflows/build.yml
    #with:
      #environment: "dev"
      #ref: ${{ inputs.ref }}
    #secrets: inherit

  load-test-email-delivery-time:
    if: ${{ (inputs.action == 'load-test-email-delivery-time') || (inputs.action == 'All') }}
    uses: ./.github/workflows/build.yml
    with:
      environment: "dev"
      ref: ${{ inputs.ref }}
      commit_sha: "0d818c38ccac687594b91fa0437ba1dffc0c00aa"
    secrets: inherit
