name: Update cached Docker image

on:
  workflow_dispatch:

jobs:
  update-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Build and cache
        uses: docker/build-push-action@v2
        with:
          file: ci/Dockerfile
          pull: true
          cache-to: type=gha,scope=api
