name: Update cached Docker image

on:
  schedule:
    # every weekday at 5am
    - cron: "0 5 * * 1-5"
  workflow_dispatch:

jobs:
  update-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and cache
        uses: docker/build-push-action@v3
        with:
          file: ci/Dockerfile
          pull: true
          cache-to: type=gha,scope=api
